# .github/workflows/dev.yml
name: Standalone CLI
on:
  push:
  pull_request:
jobs:
  machineStandalone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run skims scan
        uses: docker://docker.io/fluidattacks/skims:latest
        with:
          args: skims --strict scan skims-config.yaml